# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
end

target 'InstagramClientApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramClientApp
  firebase

  target 'InstagramClientAppTests' do
    inherit! :search_paths
    # Pods for testing
    firebase
  end

end
